<!-- NOTE: PLEASE DO NOT REMOVE THE BELLOW 3 LINES FROM YOUR HEADER FILE -->
<?php
include("language/language.php");
?>
<!-- NOTE: PLEASE DO NOT REMOVE THE ABOVE 3 LINES FROM YOUR HEADER FILE -->

<html>
<head>
  <title>DigiOz.com - Guestbook Version 1.4</title>
  <link rel="STYLESHEET" type="text/css" href="style.css">
</head>
<body bgcolor="#FFFFFF" text="#000000" link="#8080ff" vlink="#0000ff" alink="#ffff00"><center>
<h1><?php echo $headingtitletxt ?></h1>



<center>
[ <a href="guestbook.php"><b><?php echo $addentrytxt ?></b></a> ]
[ <a href="list.php"><b><?php echo $viewguestbooktxt ?></b></a> ]<br>
[ <a href="list.php"><?php echo $newpostfirsttxt ?></a> ]
[ <a href="list2.php"><?php echo $newpostlasttxt ?></a> ]</center>

<br>
<br>

<table bgcolor=#FFFFFF bordercolor=#C0C0C0 border=1 width=500><tr><td>
