<html>
<head>
  <title>DigiOz.com - Guestbook Version 1.1</title>
  <link rel="STYLESHEET" type="text/css" href="style.css">
</head>
<body bgcolor="#FFFFFF" text="#000000" link="#8080ff" vlink="#0000ff" alink="#ffff00"><center>
<h1>Guestbook</h1>



<center>
[ <a href="guestbook.php"><b>Add Entry</b></a> ]
[ <a href="list.php"><b>View Guestbook</b></a> ]<br>
[ <a href="list.php">New Posts First</a> ]
[ <a href="list2.php">New Posts Last</a> ]</center>

<br>
<br>

<table bgcolor=#FFFFFF bordercolor=#C0C0C0 border=1 width=500><tr><td>