</FONT>

</td></tr></table>
											</FONT>
										</TD>
									</TR>
									</TBODY>
									</TABLE>
								</TD>
							</TR>
							</TBODY>
							</TABLE>
<br>

</td>
<td vAlign=top width=25%>

            <TABLE cellSpacing=0 cellPadding=0 width="98%" height="150" align=center bgColor=#000000 border=0>
            <TBODY>
                   <TR>
                      	<TD>
                        	<TABLE cellSpacing=1 cellPadding=1 cellspacing=0 width="100%" height=100% border=0>
                          		<TBODY>
                          			<TR>
                            				<TD width="100%" height=20 bgColor=#314263>
									<FONT face="verdana, arial, helvetica" color=#ffffff size=2>
									<center><B>TOP 10 Forum Scripts</B></center>
									</FONT>
								</TD>
							</TR>
                          			<TR>
                         				<TD width="100%" vAlign=top bgColor=#efefef><FONT face="verdana, arial, helvetica" size=1>
								<ol type=1>
									<li><a href="http://www.phorum.org"><FONT face="verdana, arial, helvetica" size=2>Phorum</FONT></a><br>
									<li><a href="http://www.vbulletin.com"><FONT face="verdana, arial, helvetica" size=2>vBulletin</FONT></a><br>
									<li><a href="http://www.phpbb.com"><FONT face="verdana, arial, helvetica" size=2>phpBB</FONT></a><br>
									<li><a href="http://www.xmbforum.com"><FONT face="verdana, arial, helvetica" size=2>XMB Forum</FONT></a><br>
									<li><a href="http://www.invisionboard.com/"><FONT face="verdana, arial, helvetica" size=2>Invision Forum</FONT></a><br>
									<li><a href="http://www.myupb.com/"><FONT face="verdana, arial, helvetica" size=2>Ultimate PHP Board</FONT></a><br>
									<li><a href="http://www.mybboard.com/main.html"><FONT face="verdana, arial, helvetica" size=2>My Bulletin Board</FONT></a><br>
									<li><a href="http://www.wowbb.com/"><FONT face="verdana, arial, helvetica" size=2>WOW Bulletin Board</FONT></a><br>
									<li><a href="http://www.w-agora.net/en/index.php"><FONT face="verdana, arial, helvetica" size=2>W-Agora Forum</FONT></a><br>
									<li><a href="http://www.yabbforum.com/"><FONT face="verdana, arial, helvetica" size=2>YABB</FONT></a><br>
								</ol></FONT>
									</TD>
							</TR>
							</TBODY>
							</TABLE>
						</TD>
							</TR>
							</TBODY>
							</TABLE>
<br>

            <TABLE cellSpacing=0 cellPadding=0 width="98%" height="150" align=center bgColor=#000000 border=0>
            <TBODY>
                   <TR>
                      	<TD>
                        	<TABLE cellSpacing=1 cellPadding=1 cellspacing=0 width="100%" height=100% border=0>
                          		<TBODY>
                          			<TR>
                            				<TD width="100%" height=20 bgColor=#314263>
									<FONT face="verdana, arial, helvetica" color=#ffffff size=2>
									<center><B>Programming</B></center>
									</FONT>
								</TD>
							</TR>
                          			<TR>
                         				<TD width="100%" vAlign=top bgColor=#efefef><br>
<FONT face="verdana, arial, helvetica" size=2>
Need to create a custom program for your business? We can help you create Windows based Programs to help you with such tasks as generating sales reports, timesheets, client database and more. Our programmers use C++ and Visual Basic 6.0 to help you design your ideal business or home application.<br>
<center><img src="http://www.digioz.com/icons/cpp.gif"><img src="http://www.digioz.com/icons/jpp.gif"><img src="http://www.digioz.com/icons/vb6.gif"></center>
<br>
<center>[ <A href="contactus.php">Contact Us Now!</A> ]</center>											
									</FONT>								</TD>
							</TR>
							</TBODY>
							</TABLE>
						</TD>
							</TR>
							</TBODY>
							</TABLE>

</td>
</tr>
</TABLE>
</center>

<br>

<!-- Actual Body of the Display Ends Here -->

<TABLE cellSpacing=0 cellPadding=0 width="100%" background=images/footertopbg.gif border=0>
	<TBODY>
	<TR>
       	<TABLE cellSpacing=0 cellPadding=4 width="100%" bgColor=#192a3a border=0>
  			<TBODY>
  			<TR>
    				<TD width="100%">
      				<DIV align=center>
					<B><FONT face="verdana, arial, helvetica" color=#ffffff size=2>
						<A class=white href="http://www.digioz.com/index.php">Home</A>&nbsp; |&nbsp;
						<A class=white href="http://www.digioz.com/prices.php">Prices</A>&nbsp; |&nbsp;
						<A class=white href="http://www.digioz.com/clients.php">Clients</A>&nbsp; |&nbsp;
						<A class=white href="http://www.digioz.com/forum.php">Forums</A>&nbsp; |&nbsp;
						<A class=white href="http://www.digioz.com/services.php">Services</A>&nbsp; |&nbsp;
						<A class=white href="http://www.digioz.com/contactus.php">Contact Us</A>&nbsp; |&nbsp;
						<A class=white href="http://www.digioz.com/faq.php">FAQ</A>&nbsp; |&nbsp;
						<A class=white href="http://www.digioz.com/downloads.php">Downloads</A>
					</FONT></B>
					</DIV>
				</TD>
			</TR>
			</TBODY>
		</TABLE>
	</TR>
	</TBODY>
</TABLE>

<TABLE cellSpacing=0 cellPadding=4 width="100%" bgColor=#AFB1B4 border=0>
	<TBODY>
  	<TR>
		<TD width="100%"><FONT face=verdana,arial,helvetica size=1><center>© DigiOz.com 2002</center></FONT></TD>
	</TR>
	</TBODY>
</TABLE>

</BODY>
</HTML>

